name: Test
# Can be manually triggered
on:
  workflow_dispatch:
jobs:
  prepare_release:
    runs-on: ubuntu-latest
    env:
     MY_VAR: ${{ secrets.SECRET_VAR }}
    steps:
    - name: run release prepare command for freetrial
      run: |
          if [[ "$MY_VAR" == "secret value" ]]; then
            echo "OK"
          fi
